package com.learning.cruddemo.exceptions;

public enum ErrorCode {
    STUDENT_NOT_FOUND,
    TASK_NOT_FOUND,
    DUPLICATE_EMAIL,
    DUPLICATE_ROLL_NUMBER,
    INTERNAL_ERROR,
    INVALID_STATUS,
    INVALID_DUE_DATE,
    INVALID_NAME,
    INVALID_EMAIL,
    INVALID_ROLL_NUMBER,
    INVALID_TITLE,
    INVALID_STUDENT_ID,
    STUDENT_NAME_MISMATCH
}
